### ISSUE TITLE
Is this library still working or deprecated? 

### ISSUE THREAD

**Issue by sdhawan81** [RedisAI/mlflow-redisai#12]
For me when running - `mlflow deployments create -t redisai -m model-uri --name redis-key` is giving below error - 

`
    Traceback (most recent call last):
    File "/home/ubuntu/anaconda3/bin/mlflow", line 8, in <module>
    sys.exit(cli())
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mlflow/deployments/cli.py", line 145, in create_deployment
    deployment = client.create_deployment(name, model_uri, flavor, config=config_dict)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mlflow_redisai/__init__.py", line 122, in create_deployment
    flavor = get_preferred_deployment_flavor(model_config)
    File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mlflow_redisai/utils.py", line 78, in 
    get_preferred_deployment_flavor
    error_code=RESOURCE_DOES_NOT_EXIST)
    mlflow.exceptions.MlflowException: The specified model does not contain any of the supported flavors for deployment. 
    The model contains the following flavors: dict_keys(['python_function']). Supported flavors: ['torchscript', 'tensorflow']
`

**Comment by alonre24** [comment]
As far as we know, it should still work against `mlflow 1.19`. Can you share your `model-uri` so we can try to reproduce it? 
Thanks
